#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# apt-get install nasm qemu texinfo

mkdir -p /tmp/src
cd /tmp/src || exit

PREFIX="/usr/local/i386elfgcc"
TARGET=i386-elf
PATH="$PREFIX/bin:$PATH"

# binutils
BINUTILS_VERSION=2.37
curl -O http://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.gz # If the link 404's, look for a more recent version
tar xzf binutils-$BINUTILS_VERSION.tar.gz
mkdir binutils-build
cd binutils-build || exit
../binutils-$BINUTILS_VERSION/configure --target=$TARGET --enable-interwork --enable-multilib --disable-nls --disable-werror --prefix=$PREFIX 2>&1 | tee configure.log
make all install 2>&1 | tee make.log

cd ..

# gcc
GCC_VERSION=11.2.0
curl -O https://ftp.gnu.org/gnu/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz
tar xzf gcc-$GCC_VERSION.tar.gz
cd gcc-$GCC_VERSION || exit
./contrib/download_prerequisites
cd ..
mkdir gcc-build
cd gcc-build || exit
../gcc-$GCC_VERSION/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --disable-libssp --enable-languages=c --without-headers
make all-gcc 
make all-target-libgcc 
make install-gcc 
make install-target-libgcc 
cd ..

# gdb
GDB_VERSION=11.2
curl -O http://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.gz
tar xzf gdb-$GDB_VERSION.tar.gz
mkdir gdb-build
cd gdb-build || exit
export PREFIX="/usr/local/i386elfgcc"
export TARGET=i386-elf
../gdb-$GDB_VERSION/configure --target="$TARGET" --prefix="$PREFIX" --program-prefix=i386-elf-
make
make install

cd $DIR || exit