#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

apt-get install nasm qemu texinfo

mkdir /tmp/src
cd /tmp/src

PREFIX="/usr/local/i386elfgcc"
TARGET=i386-elf
PATH="$PREFIX/bin:$PATH"

# binutils
curl -O http://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.gz # If the link 404's, look for a more recent version
tar xf binutils-2.30.tar.gz
mkdir binutils-build
cd binutils-build
../binutils-2.30/configure --target=$TARGET --enable-interwork --enable-multilib --disable-nls --disable-werror --prefix=$PREFIX 2>&1 | tee configure.log
make all install 2>&1 | tee make.log

cd ..

# gcc
curl -O https://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
tar xf gcc-5.4.0.tar.bz2
cd gcc-5.4.0
./contrib/download_prerequisites
cd ..
mkdir gcc-build
cd gcc-build
../gcc-5.4.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --disable-libssp --enable-languages=c --without-headers
make all-gcc 
make all-target-libgcc 
make install-gcc 
make install-target-libgcc 
cd ..

# gdb
curl -O http://ftp.gnu.org/gnu/gdb/gdb-7.12.1.tar.gz
tar xf gdb-7.12.1.tar.gz
mkdir gdb-build
cd gdb-build
export PREFIX="/usr/local/i386elfgcc"
export TARGET=i386-elf
../gdb-7.12.1/configure --target="$TARGET" --prefix="$PREFIX" --program-prefix=i386-elf-
make
make install

cd $DIR